"""Dump flatness-map oracle vectors for the AC_INDI_OuterLoop C++ gtest (Task B1).

Prints C-array initializers for a set of FlatOutput -> RefState cases, taken
directly from indi_harness.flatness._core (the closed-form part of the S0
oracle). We dump _core (not flat_reference) because the firmware static
flat_reference reproduces the closed-form q, w (incl w_z), dw_x, dw_y, T; the
dw_z central-difference is inter-tick and validated in flight, not here.

Cases: several lemniscate_slow samples (fixed yaw, exercises p/v/a/j/s and the
tilt-driven w_z) plus synthetic yaw-varying FlatOutputs (exercises the dpsi
term of w_z and the yaw of q). Run:
    nix-shell --run "python tools/gen_flatness_oracle.py"
"""
import numpy as np
from indi_harness.trajectory import Lemniscate, FlatOutput
from indi_harness.flatness import _core
from indi_harness.outer_loop import OuterLoopINDI, OuterGains, attitude_from_thrust_dir
from indi_harness.params import QuadParams
from indi_harness import quat

M, G = 1.0, 9.81


def fmt3(v):
    return "{%.9ff,%.9ff,%.9ff}" % (v[0], v[1], v[2])


def emit(fo):
    q, w, dw_x, dw_y, T, w_z = _core(fo, M, G)
    w = np.asarray(w, float)
    print("    {%s,%s,%s,%s,%s,%.9ff,%.9ff,%.9ff,"
          % (fmt3(fo.p), fmt3(fo.v), fmt3(fo.a), fmt3(fo.j), fmt3(fo.s),
             fo.psi, fo.dpsi, fo.ddpsi))
    print("     {%.9ff,%.9ff,%.9ff,%.9ff},{%.9ff,%.9ff,%.9ff},%.9ff,%.9ff,%.9ff},"
          % (q[0], q[1], q[2], q[3], w[0], w[1], w[2], dw_x, dw_y, T))


KP = np.array([6.0, 6.0, 6.0])
KV = np.array([4.0, 4.0, 4.0])
CUTOFF, FS = 8.0, 500.0


def emit_outer(p, v, q, f_b, Om, fo):
    """Steady-state OuterLoopINDI.update: drive constant inputs until the
    Butter2 filters settle, then dump (z_b_des, T_cmd). The steady state is
    filter-family independent (both Butter2 and the firmware biquad preserve
    DC), so the firmware LowPassFilter2p reproduces it after its own settle."""
    P = QuadParams(m=M, g=G)
    ol = OuterLoopINDI(P, OuterGains(kp=KP.copy(), kv=KV.copy(), cutoff_hz=CUTOFF), FS)
    z_b_des, T_cmd = None, None
    for _ in range(3000):
        z_b_des, T_cmd = ol.update(p, v, q, f_b, Om, fo)
    T_state = P.kf * float(np.sum(np.asarray(Om) ** 2)) / P.m
    # struct: p, v, q, f_b, T_state, fo.a, fo.p, fo.v -> z_b_des, T_cmd
    print("    {%s,%s,{%.9ff,%.9ff,%.9ff,%.9ff},%s,%.9ff,"
          % (fmt3(p), fmt3(v), q[0], q[1], q[2], q[3], fmt3(f_b), T_state))
    print("     %s,%s,%s," % (fmt3(fo.a), fmt3(fo.p), fmt3(fo.v)))
    print("     {%s},%.9ff}," % (fmt3(z_b_des), T_cmd))


def emit_att(z_b_des, psi):
    z = np.asarray(z_b_des, float)
    z = z / np.linalg.norm(z)
    q = attitude_from_thrust_dir(z, psi)
    print("    {%s,%.9ff,{%.9ff,%.9ff,%.9ff,%.9ff}},"
          % (fmt3(z), psi, q[0], q[1], q[2], q[3]))


def main():
    print("// AUTO-GENERATED by indi-harness/tools/gen_flatness_oracle.py")
    print("// Oracle: indi_harness.flatness._core (m=%.1f, g=%.2f)." % (M, G))
    print("// ==== FLATNESS (Task B1) ====")
    lem = Lemniscate(amplitude=2.0, period=12.0, alt=10.0)
    for t in np.linspace(0.7, 5.3, 4):
        emit(lem.ref(t))
    # synthetic yaw-varying cases: arbitrary but physically sane a/j/s + yaw.
    rng = np.random.default_rng(0)
    for _ in range(3):
        a = rng.uniform(-4, 4, 3)
        j = rng.uniform(-6, 6, 3)
        s = rng.uniform(-8, 8, 3)
        psi = rng.uniform(-2.0, 2.0)
        dpsi = rng.uniform(-1.0, 1.0)
        ddpsi = rng.uniform(-1.0, 1.0)
        emit(FlatOutput(np.zeros(3), np.zeros(3), a, j, s, psi, dpsi, ddpsi))

    print("// ==== OUTER LOOP steady-state (Task B2), kp=6 kv=4 cutoff=8 fs=500 ====")
    Om_h = np.full(4, np.sqrt(M * G / (4.0 * QuadParams().kf)))  # hover rotor speed
    lvl = np.array([1.0, 0.0, 0.0, 0.0])
    # (a) hover, on reference: level, hover thrust, zero position/vel error.
    emit_outer(np.zeros(3), np.zeros(3), lvl,
               np.array([0.0, 0.0, -G]), Om_h,
               FlatOutput(np.zeros(3), np.zeros(3), np.zeros(3), np.zeros(3),
                          np.zeros(3), 0.0, 0.0, 0.0))
    # (b) position + velocity error, still level.
    emit_outer(np.array([0.5, -0.3, -9.7]), np.array([0.2, 0.1, -0.05]), lvl,
               np.array([0.1, -0.2, -G + 0.3]), Om_h,
               FlatOutput(np.array([1.0, 0.5, -10.0]), np.array([0.4, -0.2, 0.0]),
                          np.array([0.6, -0.4, 0.2]), np.zeros(3), np.zeros(3),
                          0.0, 0.0, 0.0))
    # (c) tilted attitude + throttle above hover + reference accel.
    q_t = quat.qexp(np.array([0.25, -0.15, 0.35]))
    emit_outer(np.array([-0.4, 0.6, -10.2]), np.array([-0.1, 0.3, 0.08]), q_t,
               np.array([0.5, 0.7, -G - 0.5]), Om_h * 1.06,
               FlatOutput(np.array([0.0, 1.0, -10.0]), np.array([-0.3, 0.5, -0.1]),
                          np.array([-1.2, 0.9, -0.5]), np.zeros(3), np.zeros(3),
                          0.6, 0.0, 0.0))

    print("// ==== attitude_from_thrust_dir (Task B2) ====")
    emit_att(np.array([0.0, 0.0, -1.0]), 0.0)         # level
    emit_att(np.array([0.2, -0.1, -0.97]), 0.5)       # mild tilt + yaw
    emit_att(np.array([-0.3, 0.4, -0.87]), -1.2)      # larger tilt + yaw
    emit_att(np.array([0.9999, 0.0, -0.0141]), 0.0)   # ~90deg pitch along heading (degenerate)


if __name__ == "__main__":
    main()
